/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.authtoken.auth;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.phenoml.api.core.ClientOptions;
import com.phenoml.api.core.MediaTypes;
import com.phenoml.api.core.ObjectMappers;
import com.phenoml.api.core.PhenomlClientApiException;
import com.phenoml.api.core.PhenomlClientException;
import com.phenoml.api.core.PhenomlClientHttpResponse;
import com.phenoml.api.core.RequestOptions;
import com.phenoml.api.resources.authtoken.auth.requests.AuthGenerateTokenRequest;
import com.phenoml.api.resources.authtoken.auth.requests.ClientCredentialsRequest;
import com.phenoml.api.resources.authtoken.auth.types.AuthGenerateTokenResponse;
import com.phenoml.api.resources.authtoken.errors.BadRequestError;
import com.phenoml.api.resources.authtoken.errors.InternalServerError;
import com.phenoml.api.resources.authtoken.errors.UnauthorizedError;
import com.phenoml.api.resources.authtoken.types.TokenResponse;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawAuthClient {
    protected final ClientOptions clientOptions;

    public RawAuthClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Obtain an access token using client credentials
     */
    public PhenomlClientHttpResponse<AuthGenerateTokenResponse> generateToken(AuthGenerateTokenRequest request) {
        return generateToken(request, null);
    }

    /**
     * Obtain an access token using client credentials
     */
    public PhenomlClientHttpResponse<AuthGenerateTokenResponse> generateToken(
            AuthGenerateTokenRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("auth/token");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PhenomlClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AuthGenerateTokenResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PhenomlClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PhenomlClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * OAuth 2.0 client credentials token endpoint (RFC 6749 §4.4).
     * Accepts client_id and client_secret in the request body (JSON or
     * form-encoded) or via Basic Auth header (RFC 6749 §2.3.1), and
     * returns an access token with expiration information.
     */
    public PhenomlClientHttpResponse<TokenResponse> getToken() {
        return getToken(ClientCredentialsRequest.builder().build());
    }

    /**
     * OAuth 2.0 client credentials token endpoint (RFC 6749 §4.4).
     * Accepts client_id and client_secret in the request body (JSON or
     * form-encoded) or via Basic Auth header (RFC 6749 §2.3.1), and
     * returns an access token with expiration information.
     */
    public PhenomlClientHttpResponse<TokenResponse> getToken(RequestOptions requestOptions) {
        return getToken(ClientCredentialsRequest.builder().build(), requestOptions);
    }

    /**
     * OAuth 2.0 client credentials token endpoint (RFC 6749 §4.4).
     * Accepts client_id and client_secret in the request body (JSON or
     * form-encoded) or via Basic Auth header (RFC 6749 §2.3.1), and
     * returns an access token with expiration information.
     */
    public PhenomlClientHttpResponse<TokenResponse> getToken(ClientCredentialsRequest request) {
        return getToken(request, null);
    }

    /**
     * OAuth 2.0 client credentials token endpoint (RFC 6749 §4.4).
     * Accepts client_id and client_secret in the request body (JSON or
     * form-encoded) or via Basic Auth header (RFC 6749 §2.3.1), and
     * returns an access token with expiration information.
     */
    public PhenomlClientHttpResponse<TokenResponse> getToken(
            ClientCredentialsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v2/auth/token");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PhenomlClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PhenomlClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, TokenResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PhenomlClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PhenomlClientException("Network error executing HTTP request", e);
        }
    }
}
