// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as phenoml from "../../../index.js";

export declare namespace AgentClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AgentClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AgentClient.Options>;

    constructor(options: AgentClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public streamChat(
        request: phenoml.agent.AgentChatRequest,
        requestOptions?: AgentClient.RequestOptions,
    ): core.HttpResponsePromise<core.Stream<phenoml.agent.AgentChatStreamEvent>> {
        return core.HttpResponsePromise.fromPromise(this.__streamChat(request, requestOptions));
    }

    private async __streamChat(
        request: phenoml.agent.AgentChatRequest,
        requestOptions?: AgentClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.Stream<phenoml.agent.AgentChatStreamEvent>>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.phenomlEnvironment.Default,
                "agent/stream-chat",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            responseType: "sse",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as core.Stream<phenoml.agent.AgentChatStreamEvent>,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.phenomlError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agent/stream-chat");
    }

    public chat(
        request: phenoml.agent.AgentChatRequest,
        requestOptions?: AgentClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__chat(request, requestOptions));
    }

    public getAgent(
        agentId: string,
        request: phenoml.agent.GetAgentRequest = {},
        requestOptions?: AgentClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getAgent(agentId, request, requestOptions));
    }

    private async __getAgent(
        agentId: string,
        request: phenoml.agent.GetAgentRequest = {},
        requestOptions?: AgentClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { version } = request;
        const _queryParams: Record<string, unknown> = { version };
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: `https://example/agent/${agentId}`,
            method: "GET",
            queryParameters: _queryParams,
        });
        if (_response.ok) return { data: _response.body, rawResponse: _response.rawResponse };
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/agent/{agent_id}");
    }

    private async __chat(
        request: phenoml.agent.AgentChatRequest,
        requestOptions?: AgentClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { "X-Phenoml-On-Behalf-Of": phenomlOnBehalfOf, ..._body } = request;
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: "https://example/agent/chat",
            method: "POST",
            body: _body,
        });
        if (_response.ok) return { data: _response.body, rawResponse: _response.rawResponse };
        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/agent/chat");
    }
}
