/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.phenoml.api.resources.authtoken.auth.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.phenoml.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AuthGenerateTokenRequest.Builder.class)
public final class AuthGenerateTokenRequest {
    private final String username;

    private final String password;

    private final Optional<String> scope;

    private final Map<String, Object> additionalProperties;

    private AuthGenerateTokenRequest(
            String username,
            String password,
            Optional<String> scope,
            Map<String, Object> additionalProperties) {
        this.username = username;
        this.password = password;
        this.scope = scope;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("username")
    public String getUsername() {
        return username;
    }

    @JsonProperty("password")
    public String getPassword() {
        return password;
    }

    @JsonProperty("scope")
    public Optional<String> getScope() {
        return scope;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    public static UsernameStage builder() {
        return new Builder();
    }

    public interface UsernameStage {
        PasswordStage username(@NotNull String username);
    }

    public interface PasswordStage {
        _FinalStage password(@NotNull String password);
    }

    public interface _FinalStage {
        AuthGenerateTokenRequest build();

        _FinalStage scope(Optional<String> scope);

        _FinalStage scope(String scope);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UsernameStage, PasswordStage, _FinalStage {
        private String username;

        private String password;

        private Optional<String> scope = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        @JsonSetter("username")
        public PasswordStage username(@NotNull String username) {
            this.username = Objects.requireNonNull(username, "username must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("password")
        public _FinalStage password(@NotNull String password) {
            this.password = Objects.requireNonNull(password, "password must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage scope(String scope) {
            this.scope = Optional.ofNullable(scope);
            return this;
        }

        @java.lang.Override
        public _FinalStage scope(Optional<String> scope) {
            this.scope = scope;
            return this;
        }

        @java.lang.Override
        public AuthGenerateTokenRequest build() {
            return new AuthGenerateTokenRequest(username, password, scope, additionalProperties);
        }
    }
}
