// This file was auto-generated by Fern from our API Definition.

import * as phenoml from "../../../src/api/index";
import { phenomlClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SummaryClient", () => {
    test("listTemplates (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            templates: [
                {
                    id: "id",
                    user_id: "user_id",
                    name: "name",
                    description: "description",
                    template: "template",
                    target_resources: ["target_resources"],
                    mode: "mode",
                    metadata: { key: "value" },
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/fhir2summary/templates")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.listTemplates();
        expect(response).toEqual({
            success: true,
            templates: [
                {
                    id: "id",
                    user_id: "user_id",
                    name: "name",
                    description: "description",
                    template: "template",
                    target_resources: ["target_resources"],
                    mode: "mode",
                    metadata: {
                        key: "value",
                    },
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
        });
    });

    test("listTemplates (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fhir2summary/templates")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.listTemplates();
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("listTemplates (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fhir2summary/templates")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.listTemplates();
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("createTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            example_summary: "Patient John Doe, age 45, presents with hypertension diagnosed on 2024-01-15.",
            target_resources: ["Patient", "Condition", "Observation"],
            mode: "mode",
        };
        const rawResponseBody = {
            success: true,
            message: "message",
            template_id: "template_id",
            template: {
                id: "id",
                user_id: "user_id",
                name: "name",
                description: "description",
                template: "template",
                target_resources: ["target_resources"],
                mode: "mode",
                metadata: { key: "value" },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };
        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.createTemplate({
            name: "name",
            example_summary: "Patient John Doe, age 45, presents with hypertension diagnosed on 2024-01-15.",
            target_resources: ["Patient", "Condition", "Observation"],
            mode: "mode",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            template_id: "template_id",
            template: {
                id: "id",
                user_id: "user_id",
                name: "name",
                description: "description",
                template: "template",
                target_resources: ["target_resources"],
                mode: "mode",
                metadata: {
                    key: "value",
                },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        });
    });

    test("createTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            example_summary: "example_summary",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.createTemplate({
                name: "name",
                example_summary: "example_summary",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.BadRequestError);
    });

    test("createTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            example_summary: "example_summary",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.createTemplate({
                name: "name",
                example_summary: "example_summary",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("createTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            example_summary: "example_summary",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/template")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.createTemplate({
                name: "name",
                example_summary: "example_summary",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("getTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            template: {
                id: "id",
                user_id: "user_id",
                name: "name",
                description: "description",
                template: "template",
                target_resources: ["target_resources"],
                mode: "mode",
                metadata: { key: "value" },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };
        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.getTemplate({
            id: "id",
        });
        expect(response).toEqual({
            success: true,
            template: {
                id: "id",
                user_id: "user_id",
                name: "name",
                description: "description",
                template: "template",
                target_resources: ["target_resources"],
                mode: "mode",
                metadata: {
                    key: "value",
                },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        });
    });

    test("getTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.getTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("getTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.getTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("getTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.getTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("getTemplate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/fhir2summary/template/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.getTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("updateTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources"],
            mode: "mode",
        };
        const rawResponseBody = {
            success: true,
            message: "message",
            template: {
                id: "id",
                user_id: "user_id",
                name: "name",
                description: "description",
                template: "template",
                target_resources: ["target_resources"],
                mode: "mode",
                metadata: { key: "value" },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        };
        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.updateTemplate({
            id: "id",
            name: "name",
            template: "template",
            target_resources: ["target_resources"],
            mode: "mode",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            template: {
                id: "id",
                user_id: "user_id",
                name: "name",
                description: "description",
                template: "template",
                target_resources: ["target_resources"],
                mode: "mode",
                metadata: {
                    key: "value",
                },
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
        });
    });

    test("updateTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.updateTemplate({
                id: "id",
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.BadRequestError);
    });

    test("updateTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.updateTemplate({
                id: "id",
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("updateTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.updateTemplate({
                id: "id",
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("updateTemplate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.updateTemplate({
                id: "id",
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("updateTemplate (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "name",
            template: "template",
            target_resources: ["target_resources", "target_resources"],
            mode: "mode",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/fhir2summary/template/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.updateTemplate({
                id: "id",
                name: "name",
                template: "template",
                target_resources: ["target_resources", "target_resources"],
                mode: "mode",
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("deleteTemplate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };
        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.deleteTemplate({
            id: "id",
        });
        expect(response).toEqual({
            success: true,
            message: "message",
        });
    });

    test("deleteTemplate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.deleteTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("deleteTemplate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.deleteTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("deleteTemplate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.deleteTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("deleteTemplate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/fhir2summary/template/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.deleteTemplate({
                id: "id",
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fhir_resources: { resourceType: "resourceType" } };
        const rawResponseBody = { success: true, message: "message", summary: "summary", warnings: ["warnings"] };
        server
            .mockEndpoint()
            .post("/fhir2summary/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.summary.create({
            fhir_resources: {
                resourceType: "resourceType",
            },
        });
        expect(response).toEqual({
            success: true,
            message: "message",
            summary: "summary",
            warnings: ["warnings"],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fhir_resources: { resourceType: "resourceType" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.create({
                fhir_resources: {
                    resourceType: "resourceType",
                },
            });
        }).rejects.toThrow(phenoml.summary.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fhir_resources: { resourceType: "resourceType" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.create({
                fhir_resources: {
                    resourceType: "resourceType",
                },
            });
        }).rejects.toThrow(phenoml.summary.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fhir_resources: { resourceType: "resourceType" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.create({
                fhir_resources: {
                    resourceType: "resourceType",
                },
            });
        }).rejects.toThrow(phenoml.summary.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fhir_resources: { resourceType: "resourceType" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.create({
                fhir_resources: {
                    resourceType: "resourceType",
                },
            });
        }).rejects.toThrow(phenoml.summary.NotFoundError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { fhir_resources: { resourceType: "resourceType" } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/fhir2summary/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.summary.create({
                fhir_resources: {
                    resourceType: "resourceType",
                },
            });
        }).rejects.toThrow(phenoml.summary.InternalServerError);
    });
});
