// This file was auto-generated by Fern from our API Definition.

import * as phenoml from "../../../src/api/index";
import { phenomlClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AgentClient", () => {
    test("streamChat (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new phenomlClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { message: "hello", agent_id: "agent-123" };
        server
            .mockEndpoint()
            .post("/agent/stream-chat")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody("event: \ndata: {\"type\":\"content_delta\",\"content\":\"hi\"}\n\n")
            .build();

        const events: phenoml.agent.AgentChatStreamEvent[] = [];
        const response = await client.agent.streamChat({ message: "hello", agent_id: "agent-123" });
        for await (const event of response.data) {
            events.push(event);
        }
        expect(events).toEqual([{ type: "content_delta", content: "hi" }]);
    });
});
